# Generated by Django 3.2.7 on 2021-09-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phieunhap', models.CharField(max_length=1000)),
                ('sohoadon', models.CharField(max_length=100)),
                ('ngaythang', models.DateTimeField()),
                ('tenvattu', models.TextField()),
            ],
        ),
    ]
